import {
  days,
  months,
  years,
  generateHours,
  generateMinutes,
} from '~/assets/js/common/dateTime.js';

export default defineEventHandler(async () => {
  return [
    {
      title: 'Дата вашего рождения',
      name: 'Birthday',
      component: 'VueSelect',
      options: [
        {
          title: 'День',
          options: days,
          value: null,
        },
        {
          title: 'Месяц',
          options: months,
          value: null,
        },
        {
          title: 'Год',
          options: years,
          value: null,
        },
      ],
      value: '',
    },
    {
      title: 'Выберите ваш пол',
      name: 'Gender',
      component: 'VCheckbox',
      subcomponent: 'VCard',
      options: [
        {
          title: 'Женский',
          value: 'woman',
          img: '/img/questions/woman.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
          rounded: true,
        },
        {
          title: 'Мужской',
          value: 'man',
          img: '/img/questions/man.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
          rounded: true,
        },
      ],
      value: '',
    },
    {
      title: 'Ваше место рождения',
      name: 'City',
      component: 'SelectInput',
      value: '',
    },
    {
      title: 'В какое время вы родились?',
      name: 'Time',
      component: 'VueSelect',
      class: 'separator',
      options: [
        {
          title: 'Час',
          options: generateHours(),
          value: null,
        },
        {
          title: 'Минута',
          options: generateMinutes(),
          value: null,
        },
      ],
      value: {},
    },
    {
      title: 'Ваше семейное положение',
      name: 'Married',
      component: 'VCheckbox',
      subcomponent: 'VCard',
      options: [
        {
          title: 'В браке',
          value: 'married',
          img: '/img/questions/married.webp',
          type: 'transparent',
          bordered: true,
        },
        {
          title: 'Помолвлен(а)',
          value: 'engaged',
          img: '/img/questions/engaged.webp',
          type: 'transparent',
          bordered: true,
        },
        {
          title: 'В отношениях',
          value: 'relationship',
          img: '/img/questions/relationship.webp',
          type: 'transparent',
          bordered: true,
        },
        {
          title: 'Запутано',
          value: 'complicated ',
          img: '/img/questions/complicated.webp',
          type: 'transparent',
          bordered: true,
        },
        {
          title: 'Не в отношениях',
          value: 'single',
          img: '/img/questions/single.webp',
          type: 'transparent',
          bordered: true,
        },
        {
          title: 'В разводе',
          value: 'divorced',
          img: '/img/questions/divorced.webp',
          type: 'transparent',
          bordered: true,
        },
      ],
      value: '',
    },
    {
      title: 'Составляли вы карту рождения раньше?',
      name: 'earlyExperience',
      component: 'VCheckbox',
      subcomponent: 'VCard',
      options: [
        {
          title: 'Составлял(а)',
          value: 'had',
          img: '/img/questions/hasnatal.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
        },
        {
          title: 'Не составляла(а)',
          value: 'notHad',
          img: '/img/questions/hasnotnatal.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
        },
      ],
      value: '',
    },
    {
      title: 'Какие темы были важнейшие в последние дни?',
      name: 'importantTopics',
      component: 'VCheckbox',
      subcomponent: 'VCard',
      options: [
        {
          title: 'Финансы',
          value: 'finances',
          img: '/img/questions/finance.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
        },
        {
          title: 'Карьера',
          value: 'career',
          img: '/img/questions/career.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
        },
        {
          title: 'Любовь',
          value: 'love',
          img: '/img/questions/love.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
        },
        {
          title: 'Здоровье',
          value: 'health',
          img: '/img/questions/health.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
        },
        {
          title: 'Семейная жизнь',
          value: 'family',
          img: '/img/questions/family.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
        },
        {
          title: 'Друзья',
          value: 'friends',
          img: '/img/questions/friends.webp',
          type: 'transparent',
          bordered: true,
          size: 'small',
        },
      ],
      value: [],
    },
  ];
});
