services:
  sobaka-site:
    image: nginx:stable
    container_name: sobakasobaka-site
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    ports:
      - '127.0.0.1:3002:80'
