version: '3.8'

services:
  nuxt-app:
    build: .
    container_name: stellar-nuxt
    ports:
      - '3000:3000'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: stellar-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - nuxt-app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
