events {
    worker_connections 1024;
}

http {
    upstream nuxt_app {
        server nuxt-app:3000;
    }

    upstream vite_static {
        server frontend-test-vite:80;
    }

    # Временно http для теста
    server {
        listen 80;
        server_name sobakasobaka.ru www.sobakasobaka.ru;

        location = /healthz {
            return 200 'ok';
            add_header Content-Type text/plain;
        }

        location / {
            proxy_pass http://frontend-test-vite:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # HTTP → HTTPS
    server {
        listen 80;
        server_name stellara.ru www.stellara.ru;
        return 301 https://www.stellara.ru$request_uri;
    }

    # stellara.ru → www.stellara.ru
    server {
        listen 443 ssl;
        server_name stellara.ru;

        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;

        return 301 https://www.stellara.ru$request_uri;
    }

    # Основной сайт
    server {
        listen 443 ssl;
        server_name www.stellara.ru;

        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;

        location / {
            proxy_pass http://nuxt_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}